name: Shell Commands Run On Push

# Events that will trigger this event
on: [push]

jobs:
  run-commands-on-linux:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  run-commands-on-windows:
    runs-on: windows-latest
    needs: ["run-commands-on-linux"]
    steps:
      - name: Get Current Directory via Powershell
        run: Get-Location
      - name: Get Current Directory via Bash
        run: pwd
        shell: bash