name: Logging different contexts

on:
  repository_dispatch:
    types: [log_contexts]

jobs:
  log_the_different_contexts:
    runs-on: ubuntu-latest
    steps:
      - name: Log GitHub context
        id: github
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Log job context
        id: job
        env:
          JOB_CONTEXT: ${{ toJSON(job) }}
        run: echo "$JOB_CONTEXT"
      # For the "steps" context, we need to assign id to the different steps
      - name: Log steps context
        id: steps
        env:
          STEPS_CONTEXT: ${{ toJSON(steps) }}
        run: echo "$STEPS_CONTEXT"
      - name: Log runner context
        id: runner
        env:
          RUNNER_CONTEXT: ${{ toJSON(runner) }}
        run: echo "$RUNNER_CONTEXT"
      - name: Log strategy context
        id: strategy
        env:
          STRATEGY_CONTEXT: ${{ toJSON(strategy) }}
        run: echo "$STRATEGY_CONTEXT"
      - name: Log matrix context
        id: matrix
        env:
          MATRIX_CONTEXT: ${{ toJSON(matrix) }}
        run: echo "$MATRIX_CONTEXT"