name: Commit from inside a Workflow

on:
  repository_dispatch:
    types: [commit]

jobs:
  create_commit_on_repository_dispatch:
    runs-on: ubuntu-latest 
    steps:
      - name: Push random file from the running virtual machine
        # We will clone our repository to this working directory
        run: |
          pwd
          echo "The directory before all the git stuff:"
          ls -a
          git init -b main
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "kenjibot@bot.bot"
          git config --global user.name "kenjibot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          echo "The directory after all the git stuff:"
          ls -a
          touch $RANDOM.txt
          ls -a
          git add -A
          git commit -m "A commit made by the bot"
          git push