name: Create issue on repository dispatch

on:
  repository_dispatch:
    types: [webhook]

jobs:
  create_issue_on_repository_dispatch:
    runs-on: ubuntu-latest 
    steps:
      - name: Push random file from the running virtual machine
        # We will clone our repository to this working directory
        run: |
          pwd
          echo "The directory before all the git stuff:"
          ls -a
          git init -b main
          git remote add origin "https://$GITHUB_ACTOR:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY.git"
          git config --global user.email "kenjibot@bot.bot"
          git config --global user.name "kenjibot"
          git fetch
          git checkout main
          git branch --set-upstream-to=origin/main
          git pull
          echo "The directory after all the git stuff:"
          ls -a
          touch $RANDOM.txt
          ls -a
          git add -A
          git commit -m "A commit made by the bot"
          git push
      - name: Create issue using REST API
        run: |
          curl --request POST \
          --url https://api.github.com/repos/${{ github.repository }}/issues \
          --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
          --header 'content-type: application/json' \
          --data '{
            "title": "Automated issue for commit: ${{ github.sha }}",
            "body": "This issue was automatically created by the GitHub Action workflow **${{ github.workflow }}**. \n\n The commit hash was: _${{ github.sha }}_."
            }' \
          --fail