name: Functions inside expressions

on:
  repository_dispatch:
    types: [functions]

jobs:
  print_out_different_available_functions:
    runs-on: ubuntu-latest
    steps:
      - name: Echo the github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Echoing the functions
        run: |
          echo ${{ contains( 'hello', 'll') }}
          echo ${{ startsWith( 'hello', 'he') }}
          echo ${{ endsWith( 'hello', 'lo') }}
          echo ${{ format( 'Hello {0}{1}{2}', 'World', '!', '!')}}