name: Job status functions

on:
  repository_dispatch:
    types: [job_status, job_status_alternative]

jobs:
  default_job:
    runs-on: ubuntu-latest
    if: github.event.action == 'job_status'
    steps:
      - name: Step 1
        run: eccho "Failed step"
        # By default is false, but if you need to continue the execution without manually adding 'if'
        # in every subsequent step, we can change continue-on-error: true
        continue-on-error: false
      - name: Step 2 (will run even with failure)
        if: failure()
        run: echo "This step was run even when the previous step failed"
      - name: Step 3 (Won't run because doesn't have the if failure check)
        run: echo "This won't run, we have to add an additional 'if' to make it run when failure"
      - name: Step 4 (Will run because we included again the if failure check)
        if: failure()
        run: echo "This won't run, we have to add an additional 'if' to make it run when failure"
  alternative_job:
    runs-on: ubuntu-latest
    if: github.event.action == 'job_status_alternative'
    steps:
      - name: Logging the step information
        run: echo "The alternative step was run"