name: Github Actions Workflow Practice

on: [push]

jobs:
  run-github-actions:
    runs-on: ubuntu-latest
    steps:
      - name: List files on current directory (Before Checkout)
        run: |
          pwd
          ls -a
      - name: Checkout (From official Github actions)
        uses: actions/checkout@v1
      - name: List files after checkout
        run: |
          pwd
          ls -a
      - name: Simple JS Action
        id: greet
        # We can also use an specific commit ID after the "@"
        uses: actions/hello-world-javascript-action@v1.1
        with:
          who-to-greet: Kenji
      - name: Log the Greeting Time
        # Usually you will find what outputs does that action make in the documentation
        run: echo "${{ steps.greet.outputs.time }}"