name: Shell Commands

# Events that will trigger this event
on: [push]

jobs:
  run-shell-command:
    runs-on: ubuntu-latest
    steps:
      - name: echo a string
        run: echo "Hello world!"
      - name: multiline script
        run: |
          node -v
          npm -v
      - name: python command
        run: |
          import platform
          print(platform.processor())
        shell: python

  Run-windows-command:
    runs-on: windows-latest
    steps:
      - name: Get Current Directory via Powershell
        run: Get-Location
      - name: Get Current Directory via Bash
        run: pwd
        shell: bash